### ISSUE TITLE
How does the Delta table resource work?

### ISSUE THREAD

**Issue by gab-txt** [pulumi/pulumi-databricks#552]
## Questions

In short, these are the questions I have (context below):

1. Can the Databricks Pulumi provider create the Delta log too when creating the table?
2. Is it possible to update table columns, properties and so on?

### Question 1: table creation

This is how I'm trying to create a table:

```python
table_resource = table.Table(
    table_name,
    catalog_name=catalog,
    schema_name=schema,
    name=table_name,
    columns=[
        table.TableColumnArgs(
            name="col1", position=0, type_name="STRING", type_text="varchar(64)", comment="first column",
            type_json="{\"name\":\"col1\",\"type\":\"varchar(64)\",\"nullable\":true,\"metadata\":{}}",
        ),
        table.TableColumnArgs(
            name="col2", position=1, type_name="INT", type_text="int", comment="second column revised comment",
            type_json="{\"name\":\"col2\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}",
        ),
    ],
    data_source_format="DELTA",
    table_type="EXTERNAL",
    storage_location=f"s3://<REDACTED>",
)
```

When run, this code does create the table in the catalog but it does not create the delta log, so the table is broken (it's not possible to insert data, it's not possible to query the table): [this issue](https://github.com/pulumi/pulumi-databricks/issues/144) describes the same problem.

However, if I use something like `df.write.format("delta").mode("overwrite").save("s3://<REDACTED>")` to **first write data to the s3 path, then everything works**.

**Is there a way to have Pulumi create the Delta log too, so that it's possible to write to the Delta table using its name instead of the path?** ([this comment](https://github.com/pulumi/pulumi-databricks/issues/69#issuecomment-1445787314) suggests it's not possible...)

### Question 2: table update

Once the table is created and operational (the delta log exists), I'm trying to update it by for instance adding a column. Pulumi does realize that the resource must be updated but `pulumi up` fails with
```
cannot update table: A table's Delta metadata can only be changed from a cluster or warehouse
```
which to me is not very clear as an error: **is it because I'm doing something wrong or because the SDK is not able to update the resource?**

Comments in [this thread](https://community.databricks.com/t5/data-engineering/best-way-to-automatically-update-a-delta-table-schema/td-p/27317) suggest that the provider cannot update the table: is it true?

**Comment by guineveresaenger** [comment]
Hi @gab-txt - thank you for raising this issue. Your questions touch on missing functionality for the `Table` (specifically Unity Catalog Table) resource in both the upstream Terraform provider (which this provider is based on) _and_ the Databricks API. It appears that currently the API [does not support Updates](https://docs.databricks.com/api/workspace/tables) fully at this time.

Databricks Terraform provider maintainers decided to [not officially support this resource and remove documentation](https://github.com/databricks/terraform-provider-databricks/issues/2009) for the time being due to issues during Create as well as Update. At Pulumi, we document every resource we find in the schema; we regret that in this case this resulted in unknowingly using a nonworkable resource. I will file an issue to ensure we add a disclaimer to the `Table` resource to this point.

Unfortunately this does sound as though the underlying API is fundamentally lacking here, and there's not much we can do on our end. As soon as this endpoint is fully supported, and the upstream provider implements the functionality, we will pull in those changes.

**Comment by gab-txt** [comment]
Hi @guineveresaenger, it's unfortunate that the `Table` resource is nonworkable, but it's good to know what is and isn't available for now.

Thanks for proposing to add a disclaimer to the current documentation, this could save a lot of time for the ones that want to try it 🙂
